version: '2.1'
services:
  etcd1:
    image: quay.io/coreos/etcd:v3.2.5
    networks:
      - etcd
    ports:
      - 23791:2379
      - 23801:2380
    volumes:
      - ./certs/:/srv/
      - /srv/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node1
      ETCD_DATA_DIR: /etcd-data/etcd1.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
  etcd2:
    image: quay.io/coreos/etcd:v3.2.5
    networks:
      - etcd
    ports:
      - 23792:2379
      - 23802:2380
    volumes:
      - ./certs/:/srv/
      - /srv/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node2
      ETCD_DATA_DIR: /etcd-data/etcd2.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
      ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
  etcd3:
    image: quay.io/coreos/etcd:v3.2.5
    networks:
      - etcd
    ports:
      - 23793:2379
      - 23803:2380
    volumes:
      - ./certs/:/srv/
      - /srv/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node3
      ETCD_DATA_DIR: /etcd-data/etcd3.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
      ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379

  skydns:
    image: skynetservices/skydns
    networks:
      - etcd
    ports:
      - "5354:5354"
      - "5354:5354/udp"

    environment:
      ETCD_MACHINES: http://etcd1:2379

networks:
  etcd:
